### PR TITLE
New chess pieces

### PR DESCRIPTION
**Pull request by elyasmehtabuddin**
Solves https://github.com/fohristiwhirl/nibbler/issues/109
Has ALL the themes and adds a new menu option to change themes.
The theme change will only take in effect when the application is restarted, I was hoping in getting some guidance in how to do a hot-reload instead? I am fine with how it is now though

When viewing the diff filter out the svg and png

### CODE REVIEW

**Comment by CiriousJoker** [comment]
What do you mean by "ALL"? Is this list based on anything?

**Comment by fohristiwhirl** [comment]
I include the set I do since I believe it's GPL'd, I can't include all of these.

So I don't promise I'm going to accept this.

For hot reload, if you can arrange for the "hub" object (which is "this" in `95_renderer.js`) to get

`hub.friendly_draws = New2DArray(8, 8);`

Should I think be enough to make it redraw properly.

**Comment by elyasmehtabuddin** [comment]
> What do you mean by "ALL"? Is this list based on anything?

everything from chess.com, lichess, and chess24 I could get my hands on.

what I can do for this PR is remove all the themes except for maybe one or two lichess ones, then I will have another github repo if people want to download extra themes

I will try and also work on the hot reloading as well

**Comment by elyasmehtabuddin** [comment]
@fohristiwhirl I removed all the themes except for 1 theme from lichess repo which should be fine. Also I added board themes and there is hot reload for that and pieces as well

**Comment by fohristiwhirl** [comment]
Right, I feel you're making it way more complex than it needs to be. I've added a [commit](https://github.com/fohristiwhirl/nibbler/commit/42b19120834bf9633625cefcbe747cc2f7ed2478) that does most of what's needed, I feel.

**Comment by elyasmehtabuddin** [comment]
@fohristiwhirl 
I see... I imagine moving forward it might be better to set the default board to an image instead (like the pieces) so I don't have these if statements everywhere? But I do like the feature of being able to set the dark and light color squares in the config... hmmm

**Comment by elyasmehtabuddin** [comment]
Alright have a look at the 'board' changes I made, I can try and revert my 'piece' changes to whats on master right now tomorrow.
What I do now is treat the board as an image always and if we have no theme selected then the config colors are used to make an 8x8 png image to base64 which will be the image

**Comment by fohristiwhirl** [comment]
I had my own go at it, which I guess is working. Give it a try.

**Comment by fohristiwhirl** [comment]
I was talking on Discord with someone about these things and sort of assumed you were him, I think that was not so, sorry for any lack of communication...

**Pull request closed without merging**
