### PR TITLE
select number of threads

### PR DESCRIPTION
**Pull request by ra1u**
This allows selecting number of threads. By default leela is using 2 threads.

### CODE REVIEW

**Comment by fohristiwhirl** [comment]
Hmm - the impression I get is that normally the default thread count is correct. In any case, for advanced options you can always just edit the options part of config.json...

**Comment by ra1u** [comment]
My cpu has 8 threads and default is 2. https://github.com/LeelaChessZero/lc0/blob/06748a4a35b297164e36400a576bc64031fa0415/src/engine.cc#L39

**Comment by fohristiwhirl** [comment]
As I understand it, mostly the CPU is just used to feed stuff to the GPU, the true bottleneck. I've heard that more threads can actually be worse.

Are you getting a node per second increase with more threads?

**Comment by ra1u** [comment]
I am running blas (cpu). I do not have gpu and this option correlates with strength. For users with gpu this probably does not mater that much.

**Comment by fohristiwhirl** [comment]
Alright let's do it.

**Pull request merged**
